import singer
import pandas as pd
import hashlib
import os
from datetime import datetime

STREAM_NAME = 'combined_cgm_tracing'

def get_pk(p_id, dt):
    """Creates a unique deterministic hash for the record."""
    return hashlib.md5(f"{p_id}{dt}".encode()).hexdigest()

def transform_abbott(p_id, row):
    """Standardizes Abbott row format to DRH format."""
    # Abbott format: YYYY/MM/DD HH:MM
    dt_obj = datetime.strptime(row['Device Timestamp'], '%Y/%m/%d %H:%M')
    dt_str = dt_obj.strftime('%Y-%m-%d %H:%M:%S')
    return {
        'id': get_pk(p_id, dt_str),
        'participant_id': p_id,
        'date_time': dt_str,
        'cgm_value': float(row['Historic Glucose mg/dL'])
    }

def main():
    # 1. Emit SCHEMA
    schema = {
        'properties': {
            'id': {'type': 'string'},
            'participant_id': {'type': 'string'},
            'date_time': {'type': 'string', 'format': 'date-time'},
            'cgm_value': {'type': 'number'}
        }
    }
    singer.write_schema(STREAM_NAME, schema, ['id'])
    
    # 2. DEFINED PATHS
    demo_file = "./diabetes_research_data_7days/abbott/demographics_abbott.csv"
    data_folder = "./diabetes_research_data_7days/abbott/"
    
    if not os.path.exists(demo_file):
        print(f"Error: Demographics not found at {demo_file}", file=sys.stderr)
        return

    # 3. LOOP THROUGH DEMOGRAPHICS
    demo_df = pd.read_csv(demo_file)
    processed_subjects = []

    for _, patient in demo_df.iterrows():
        p_id = patient['USUBJID']
        # Look for the specific file generated by main.py: {p_id}_libre.csv
        filename = f"{p_id}_libre.csv"
        file_path = os.path.join(data_folder, filename)
        
        if os.path.exists(file_path):
            df = pd.read_csv(file_path)
            
            # Filter for Record Type 0 (Historic Glucose)
            if 'Record Type' in df.columns:
                df = df[df['Record Type'] == 0].dropna(subset=['Historic Glucose mg/dL'])
            
            # 4. EMIT RECORDS
            for _, row in df.iterrows():
                record = transform_abbott(p_id, row)
                singer.write_record(STREAM_NAME, record)
            
            processed_subjects.append(p_id)

    # 5. EMIT STATE
    # This shows which subjects from the demographics were successfully synced
    singer.write_state({"last_processed_subjects": processed_subjects})

if __name__ == "__main__":
    import sys
    main()